[project]
name = "crewai-custom-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "crewai[tools]==0.95.0",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.38",
]
